include $(srctree)/drivers/misc/mediatek/Makefile.custom

# In case the platform does NOT support this type of sensors

obj-$(CONFIG_MTK_GFX1XM)   +=  gfx1xm/

obj-$(CONFIG_FINGERPRINT_GOODIX_GF516M)	+=  gf516m/

