include $(srctree)/drivers/misc/mediatek/Makefile.custom


ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/ft5436_zal1518/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/

obj-y	+=  focaltech_driver.o
obj-y	+=  focaltech_ctl.o
obj-y	+=  focaltech_ex_fun.o
obj-y	+=  focaltech_monitor.o
